using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Layout;
using Avalonia.Media;
using SOCYVIA.Models;
using SOCYVIA.Repositories;
using SOCYVIA.Services;

namespace SOCYVIA.Views;

public sealed class AnalysisWorkspaceView : UserControl
{
    private readonly Study _study;private AnalysisDataset? _dataset;private DataQualityResult? _quality;
    private readonly ComboBox _outcome=new(){MinWidth=250};private readonly ComboBox _predictor=new(){ItemsSource=new[]{"Group","Condition"},SelectedIndex=1};
    private readonly ComboBox _method=new(){SelectedIndex=0};
    private readonly ComboBox _classification=new(){SelectedIndex=2};
    private readonly StackPanel _qualityPanel=new(){Spacing=5};private readonly StackPanel _recommendationPanel=new(){Spacing=5};private readonly StackPanel _resultPanel=new(){Spacing=7};private readonly StackPanel _plotPanel=new(){Spacing=6};private readonly TextBlock _busy=new(){IsVisible=false};
    private List<AnalysisVariable> _numeric=[];

    public AnalysisWorkspaceView(Study study)
    {
        _study=study;FlowDirection=LocalizationService.IsArabic?FlowDirection.RightToLeft:FlowDirection.LeftToRight;
        _method.ItemsSource=MethodChoices();_classification.ItemsSource=ClassificationChoices();
        var panel=new StackPanel{Spacing=14,Margin=new Thickness(0)};panel.Children.Add(new TextBlock{Text=T("محرك التحليل العلمي","Scientific Analysis Engine"),Classes={"pageTitle"}});panel.Children.Add(new TextBlock{Text=T("حدد البيانات والمتغيرات ثم راجع الجودة والمنطق التحليلي قبل الحساب","Define the dataset and variables, then inspect quality and analytic rationale before computation"),Foreground=Brush("#66758A"),TextWrapping=TextWrapping.Wrap});
        var selectors=new Grid{ColumnDefinitions=new ColumnDefinitions("*,12,*,12,*,12,*")};selectors.Children.Add(Field(T("النتيجة","Outcome"),_outcome));var predictorField=Field(T("متغير التجميع","Grouping variable"),_predictor);Grid.SetColumn(predictorField,2);selectors.Children.Add(predictorField);var methodField=Field(T("الطريقة","Method"),_method);Grid.SetColumn(methodField,4);selectors.Children.Add(methodField);var classField=Field(T("التصنيف","Classification"),_classification);Grid.SetColumn(classField,6);selectors.Children.Add(classField);panel.Children.Add(Card(selectors));
        _outcome.SelectionChanged+=(_,_)=>Recommend();_predictor.SelectionChanged+=(_,_)=>Recommend();
        var refresh=Button(T("تحديث مجموعة البيانات","Refresh dataset"));refresh.Click+=async(_,_)=>await ReloadAsync();var run=Button(T("حساب وحفظ التحليل","Compute and save analysis"),true);run.Click+=async(_,_)=>await RunAsync();var actions=new StackPanel{Orientation=Orientation.Horizontal,Spacing=8,Children={refresh,run}};panel.Children.Add(actions);_busy.Text=T("جار إعداد البيانات وإجراء الحساب خارج واجهة المستخدم","Preparing data and computing off the UI thread");panel.Children.Add(_busy);
        panel.Children.Add(Section(T("جودة البيانات","Data quality"),_qualityPanel));panel.Children.Add(Section(T("قرار التحليل","Analysis decision"),_recommendationPanel));panel.Children.Add(Section(T("النتائج المهيكلة","Structured results"),_resultPanel));panel.Children.Add(Section(T("مقارنة المجموعات","Group comparison"),_plotPanel));Content=new ScrollViewer{Content=panel,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};AttachedToVisualTree+=async(_,_)=>await ReloadAsync();
    }

    public async Task ReloadAsync(){SetBusy(true);try{var isDemo=DemoAccessPolicy.IsDemoStudy(_study);_dataset=await AnalysisDatasetService.BuildParticipantDatasetAsync(_study.Id,isDemo);_quality=DataQualityService.Evaluate(_dataset);_numeric=_dataset.Variables.Where(item=>item.DataType=="Double").ToList();_outcome.ItemsSource=_numeric.Select(ResearchVariableDisplayService.WithMeasurementLevel).ToArray();if(_numeric.Count>0)_outcome.SelectedIndex=Math.Clamp(_outcome.SelectedIndex,0,_numeric.Count-1);RenderQuality();Recommend();RenderEmptyResult();}catch(Exception ex){ApplicationDiagnosticsService.LogException(ex,"Load analysis workspace");_resultPanel.Children.Clear();_resultPanel.Children.Add(Text(T("تعذر بناء مجموعة البيانات","The analysis dataset could not be built"),"#B8384F"));}finally{SetBusy(false);}}
    private void Recommend(){_recommendationPanel.Children.Clear();if(_dataset is null||_outcome.SelectedIndex<0||_outcome.SelectedIndex>=_numeric.Count)return;var outcome=_numeric[_outcome.SelectedIndex];var groupId=_predictor.SelectedIndex==0?"group":"condition";var predictor=_dataset.Variables.FirstOrDefault(item=>item.Id==groupId)??new AnalysisVariable{Id=groupId,Name=groupId=="group"?T("المجموعة","Group"):T("الشرط","Condition"),DataType="String",MeasurementLevel=MeasurementLevels.Nominal};var groupCount=_dataset.Rows.Select(row=>groupId=="group"?row.GroupName:row.ConditionName).Where(value=>value is not null).Distinct().Count();var recommendation=AnalysisDecisionEngine.Recommend(outcome,predictor,groupCount,false,_dataset.Rows.Count);var recommended=MethodChoices().FirstOrDefault(item=>item.Id==recommendation.RecommendedMethod);_recommendationPanel.Children.Add(Text($"{T("الطريقة المقترحة","Recommended method")}: {recommended?.Label??recommendation.RecommendedMethod}","#1E3A66",true));foreach(var rationale in recommendation.Rationale)_recommendationPanel.Children.Add(Text("• "+rationale,"#52647C"));foreach(var warning in recommendation.Warnings)_recommendationPanel.Children.Add(Text("⚠ "+warning,"#9A650E"));if(_method.SelectedIndex==0&&recommended is not null)_method.SelectedItem=recommended;}
    private async Task RunAsync(){if(_dataset is null||_outcome.SelectedIndex<0){ShowInsufficientData();return;}var outcome=_numeric[_outcome.SelectedIndex];var available=_dataset.Rows.Count(row=>row.NumericValues.GetValueOrDefault(outcome.Id).HasValue);if(available<2){ShowInsufficientData();return;}SetBusy(true);try{var method=(_method.SelectedItem as Choice)?.Id??"DESCRIPTIVE";var classification=(_classification.SelectedItem as Choice)?.Id??AnalysisClassifications.Exploratory;var specification=new AnalysisSpecification{StudyId=_study.Id,Name=$"{(_method.SelectedItem as Choice)?.Label??method}: {ResearchVariableDisplayService.Label(outcome)}",ResearchQuestion=_study.ResearchQuestion,Classification=classification,OutcomeVariableId=outcome.Id,PredictorVariableId=_predictor.SelectedIndex==0?"group":"condition",AnalysisFamily="GROUP_COMPARISON",Method=method,ConfidenceLevel=0.95,MissingDataHandling="COMPLETE_CASE",MultipleComparisonMethod="NONE",IsDemo=DemoAccessPolicy.IsDemoStudy(_study)};await AnalysisRepository.SaveSpecificationAsync(specification);var execution=await ScientificAnalysisEngine.ExecuteAsync(_dataset,specification);await AnalysisRepository.SaveExecutionAsync(execution,_dataset.Exclusions);RenderResult(specification,execution);RenderPlot(specification.OutcomeVariableId);}catch(Exception ex){ApplicationDiagnosticsService.LogException(ex,"Compute analysis");_resultPanel.Children.Clear();_resultPanel.Children.Add(Text(T("فشل الحساب بأمان وتم حفظ تشخيص محلي","Computation failed safely and a local diagnostic was recorded"),"#B8384F"));}finally{SetBusy(false);}}
    private void RenderQuality(){_qualityPanel.Children.Clear();if(_quality is null)return;_qualityPanel.Children.Add(Metrics((T("العدد الكلي","Total N"),_quality.TotalN.ToString()),(T("المشمول","Included"),_quality.IncludedN.ToString()),(T("المستبعد","Excluded"),_quality.ExcludedN.ToString()),(T("جلسات غير مكتملة","Incomplete sessions"),_quality.SessionWarnings.Count.ToString())));var missing=_quality.MissingByVariable.Where(pair=>pair.Value>0).OrderByDescending(pair=>pair.Value).Take(6).ToArray();_qualityPanel.Children.Add(Text(missing.Length==0?T("لا توجد قيم مفقودة في المتغيرات الرقمية المتاحة","No missing values in the available numeric variables"):string.Join("  •  ",missing.Select(pair=>$"{pair.Key}: {pair.Value}")),"#52647C"));if(_quality.ConstantVariables.Count>0)_qualityPanel.Children.Add(Text($"{T("متغيرات ثابتة","Constant variables")}: {string.Join(", ",_quality.ConstantVariables)}","#9A650E"));}
    private void RenderResult(AnalysisSpecification specification,AnalysisExecution execution){_resultPanel.Children.Clear();_resultPanel.Children.Add(Text($"{StatusLabel(execution.Status)}  ·  {ClassificationLabel(specification.Classification)}  ·  {execution.EngineVersion}",execution.Status==AnalysisStatuses.Computed?"#177A5B":"#9A650E",true));if(execution.Result is null){_resultPanel.Children.Add(Text(execution.ErrorDetail??string.Join(" ",execution.Warnings),"#B8384F"));return;}var result=execution.Result;_resultPanel.Children.Add(Metrics(("N",result.N.ToString()),(T("الإحصائية","Statistic"),Format(result.Statistic)),("p",FormatP(result.PValue)),(T("التقدير","Estimate"),Format(result.Estimate))));if(result.EffectSize is not null)_resultPanel.Children.Add(Text($"{T("حجم الأثر","Effect size")}: {result.EffectSize.Method} = {Format(result.EffectSize.Value)} — {result.EffectSize.Definition}","#273850"));if(result.ConfidenceInterval is not null)_resultPanel.Children.Add(Text($"{result.ConfidenceInterval.ConfidenceLevel:P0} CI [{Format(result.ConfidenceInterval.Lower)}, {Format(result.ConfidenceInterval.Upper)}] · {result.ConfidenceInterval.Method}","#273850"));_resultPanel.Children.Add(Text(result.CanonicalSummary,"#52647C"));_resultPanel.Children.Add(Text($"Dataset SHA-256: {execution.DatasetHash}","#758297"));foreach(var diagnostic in result.Diagnostics)_resultPanel.Children.Add(Text($"{diagnostic.Code}: {diagnostic.Message}",diagnostic.Severity=="WARNING"?"#9A650E":"#66758A"));foreach(var warning in result.Warnings)_resultPanel.Children.Add(Text("⚠ "+warning,"#9A650E"));}
    private void RenderPlot(string variableId){_plotPanel.Children.Clear();if(_dataset is null)return;var grouped=_dataset.Rows.Where(row=>row.NumericValues.GetValueOrDefault(variableId).HasValue).GroupBy(row=>_predictor.SelectedIndex==0?row.GroupName:row.ConditionName).Where(group=>group.Key is not null).Select(group=>(Name:group.Key!,Values:group.Select(row=>row.NumericValues[variableId]!.Value).ToArray())).ToArray();if(grouped.Length==0){_plotPanel.Children.Add(Text(T("لا توجد قيم قابلة للرسم","No plottable values"),"#758297"));return;}var max=Math.Max(1,grouped.Max(group=>group.Values.Average()));foreach(var group in grouped){var descriptive=ScientificStatistics.Describe(group.Values.Cast<double?>());var row=new Grid{ColumnDefinitions=new ColumnDefinitions("180,*,90"),Margin=new Thickness(0,3)};row.Children.Add(Text(group.Name,"#273850",true));var track=new Border{Height=12,Background=Brush("#E8EDF5"),CornerRadius=new CornerRadius(4),HorizontalAlignment=HorizontalAlignment.Stretch};var bar=new Border{Width=Math.Max(4,300*group.Values.Average()/max),Height=12,Background=Brush("#2563EB"),CornerRadius=new CornerRadius(4),HorizontalAlignment=HorizontalAlignment.Left};var overlay=new Grid{Children={track,bar}};Grid.SetColumn(overlay,1);row.Children.Add(overlay);var value=Text($"M {descriptive.Mean:0.00} · n {descriptive.N}","#52647C");Grid.SetColumn(value,2);row.Children.Add(value);_plotPanel.Children.Add(row);} _plotPanel.Children.Add(Text(T("يبدأ المحور من الصفر، وتمثل الأعمدة المتوسط الوصفي فقط","Axis begins at zero; bars show descriptive means only"),"#758297"));}
    private void RenderEmptyResult(){_resultPanel.Children.Clear();_resultPanel.Children.Add(Text(T("اختر المتغير والطريقة ثم نفذ التحليل","Select a variable and method, then compute the analysis"),"#758297"));_plotPanel.Children.Clear();}
    /// <summary>Uses only completed eligible, synchronized remote records for real-study analysis.</summary>
    public async Task ReloadRemoteAsync(){SetBusy(true);try{_dataset=await RemoteAnalysisDatasetService.BuildCompletedEligibleAsync(_study.Id);_quality=DataQualityService.Evaluate(_dataset);_numeric=_dataset.Variables.Where(item=>item.DataType=="Double").ToList();_outcome.ItemsSource=_numeric.Select(ResearchVariableDisplayService.WithMeasurementLevel).ToArray();if(_numeric.Count>0)_outcome.SelectedIndex=Math.Clamp(_outcome.SelectedIndex,0,_numeric.Count-1);RenderQuality();Recommend();RenderEmptyResult();}catch(Exception ex){ApplicationDiagnosticsService.LogException(ex,"Load remote analysis workspace");_resultPanel.Children.Clear();_resultPanel.Children.Add(Text(T("تعذر بناء مجموعة البيانات التحليلية","The analysis dataset could not be built"),"#B8384F"));}finally{SetBusy(false);}}
    private void ShowInsufficientData(){_resultPanel.Children.Clear();_resultPanel.Children.Add(Text(T("البيانات غير كافية لإجراء هذا التحليل","Insufficient data for this analysis."),"#9A650E",true));_resultPanel.Children.Add(Text(T("أكمل جمع بيانات المشاركين أو اختر متغيرات متوافقة مع طريقة التحليل.","Collect additional participant data or select compatible variables."),"#52647C"));}
    private void SetBusy(bool value){_busy.IsVisible=value;IsEnabled=!value||_busy.IsVisible;}
    private static Border Section(string title,Control child)=>Card(new StackPanel{Spacing=8,Children={new TextBlock{Text=title,Classes={"sectionTitle"}},child}});
    private static Border Card(Control child)=>new(){Background=Brush("#FFFFFF"),BorderBrush=Brush("#DCE3ED"),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(10),Padding=new Thickness(14),Child=child};
    private static StackPanel Field(string label,Control control)=>new(){Spacing=5,Children={new TextBlock{Text=label,Classes={"metadata"}},control}};
    private static Button Button(string label,bool primary=false){var button=new Button{Content=label,HorizontalContentAlignment=HorizontalAlignment.Center};button.Classes.Add(primary?"primary":"secondary");return button;}
    private static TextBlock Text(string value,string color,bool bold=false)=>new(){Text=value,Foreground=Brush(color),FontWeight=bold?FontWeight.SemiBold:FontWeight.Normal,TextWrapping=TextWrapping.Wrap};
    private static Grid Metrics(params (string Label,string Value)[] values){var grid=new Grid{ColumnDefinitions=new ColumnDefinitions(string.Join(',',values.Select(_=>"*")))};for(var index=0;index<values.Length;index++){var panel=new StackPanel{Spacing=2,Children={Text(values[index].Value,"#1E3A66",true),Text(values[index].Label,"#758297")}};Grid.SetColumn(panel,index);grid.Children.Add(panel);}return grid;}
    private static string Format(double? value)=>value.HasValue&&double.IsFinite(value.Value)?value.Value.ToString("0.####",CultureInfo.InvariantCulture):"—";private static string FormatP(double? value)=>!value.HasValue?"—":value.Value<0.001?"< 0.001":value.Value.ToString("0.###",CultureInfo.InvariantCulture);
    private static Choice[] MethodChoices()=>[new("DESCRIPTIVE",T("إحصاءات وصفية","Descriptive statistics")),new("WELCH_T",T("اختبار t لويلش","Welch t-test")),new("INDEPENDENT_T",T("اختبار t المستقل","Independent-samples t-test")),new("MANN_WHITNEY_U",T("اختبار مان–ويتني","Mann–Whitney U")),new("ONE_WAY_ANOVA",T("تحليل التباين أحادي الاتجاه","One-way ANOVA")),new("KRUSKAL_WALLIS",T("اختبار كروسكال–واليس","Kruskal–Wallis")),new("PEARSON_R",T("ارتباط بيرسون","Pearson correlation")),new("SPEARMAN_RHO",T("ارتباط سبيرمان","Spearman correlation")),new("CHI_SQUARE",T("اختبار كاي تربيع","Chi-square test")),new("FISHER_EXACT",T("اختبار فيشر الدقيق","Fisher exact test"))];
    private static Choice[] ClassificationChoices()=>[new(AnalysisClassifications.Primary,T("أساسي","Primary")),new(AnalysisClassifications.Secondary,T("ثانوي","Secondary")),new(AnalysisClassifications.Exploratory,T("استكشافي","Exploratory"))];
    private static string StatusLabel(string value)=>value switch{AnalysisStatuses.Computed=>T("تم الحساب","Computed"),AnalysisStatuses.InsufficientData=>T("بيانات غير كافية","Insufficient data"),AnalysisStatuses.UnsupportedDesign=>T("تصميم غير مدعوم","Unsupported design"),AnalysisStatuses.InvalidConfiguration=>T("إعداد غير صالح","Invalid configuration"),AnalysisStatuses.ComputationError=>T("خطأ في الحساب","Computation error"),_=>T("جاهز","Ready")};
    private static string ClassificationLabel(string value)=>ClassificationChoices().FirstOrDefault(item=>item.Id==value)?.Label??value;
    private sealed record Choice(string Id,string Label){public override string ToString()=>Label;}
    private static string T(string ar,string en)=>UiTextService.Localized(ar,en);private static SolidColorBrush Brush(string value)=>new(Color.Parse(value));
}
