/* Deterministic, read-only data adapter for the shared participant renderer. */
window.SocyviaDemoExperimentPackage={
  defaultRuntimeLanguage:"en", estimatedDurationMinutes:4,
  researcher:{name:{en:"SOCYVIA Research Team",ar:"فريق أبحاث SOCYVIA"},role:{en:"Synthetic product demonstration",ar:"عرض توضيحي اصطناعي للمنتج"}},
  study:{title:{en:"Digital Engagement Visibility Study — Demo",ar:"دراسة إتاحة مؤشرات التفاعل الرقمي — عرض توضيحي"},description:{en:"This synthetic demonstration presents the same SOCYVIA participant journey used by local Preview and published studies. No research data is recorded.",ar:"يعرض هذا النموذج الاصطناعي مسار المشارك نفسه المستخدم في المعاينة المحلية والدراسات المنشورة. لا يتم تسجيل أي بيانات بحثية."},instructions:{en:"Review each post naturally. You may use the available interaction controls before completing the feed.",ar:"راجع كل منشور بصورة طبيعية. يمكنك استخدام عناصر التفاعل المتاحة قبل إكمال الخلاصة."},privacy:{en:"This is a read-only synthetic product demonstration.",ar:"هذا عرض توضيحي اصطناعي للمنتج للقراءة فقط."},consentText:{en:"I understand that this is a synthetic product demonstration and no research data will be recorded.",ar:"أفهم أن هذا عرض توضيحي اصطناعي للمنتج وأنه لن يتم تسجيل بيانات بحثية."}},
  orderedStimuli:[
    {stimulusId:"demo-image",contentId:"demo-image",title:"Community stories and social signals",body:"A synthetic example of a participant-facing image post. The feed, controls, and presentation are shared with SOCYVIA Preview and Live mode.",media:{kind:"image",url:"/experimentfeed/demo-media/sport-supporters.jpg",alt:"Synthetic community gathering"},interactions:{like:true,comment:true,readMore:true,save:true,share:true}},
    {stimulusId:"demo-video",contentId:"demo-video",title:"A short media stimulus",body:"This synthetic video demonstrates the same managed-media presentation used by current-study preview and published experiments.",media:{kind:"video",url:"/experimentfeed/demo-media/socyvia-demo-video.mp4",alt:"Synthetic SOCYVIA demonstration video"},interactions:{like:true,comment:true,readMore:true,save:true,share:true}},
    {stimulusId:"demo-audio",contentId:"demo-audio",title:"Audio stimulus example",body:"This synthetic audio post completes the deterministic Demo journey without sending telemetry or questionnaire responses.",media:{kind:"audio",url:"/experimentfeed/demo-media/socyvia-ambient-demo.mp3",alt:"Synthetic ambient audio"},interactions:{like:true,comment:true,readMore:true,save:true,share:true}}
  ],
  questionnaires:{
    PRE:{id:"demo-pre",versionId:"demo-pre-v1",stage:"PRE",title:"Before the feed",description:"Synthetic demonstration questionnaire",localizations:{ar:{title:"قبل الخلاصة",description:"استبيان توضيحي اصطناعي"}},items:[{id:"demo-pre-engagement",type:"LIKERT",question:"How often do you notice engagement indicators in social feeds?",localizations:{ar:{question:"كم مرة تلاحظ مؤشرات التفاعل في الخلاصات الاجتماعية؟"}},required:true,order:1,configuration:{minimum:1,maximum:5,minimumLabel:{en:"Never",ar:"أبدا"},maximumLabel:{en:"Very often",ar:"كثيرا جدا"}}}]},
    POST:{id:"demo-post",versionId:"demo-post-v1",stage:"POST",title:"After the feed",description:"Synthetic demonstration questionnaire",localizations:{ar:{title:"بعد الخلاصة",description:"استبيان توضيحي اصطناعي"}},items:[{id:"demo-post-clarity",type:"LIKERT",question:"How clear was the participant experience?",localizations:{ar:{question:"ما مدى وضوح تجربة المشارك؟"}},required:true,order:1,configuration:{minimum:1,maximum:5,minimumLabel:{en:"Not clear",ar:"غير واضح"},maximumLabel:{en:"Very clear",ar:"واضح جدا"}}}]}
  },
  allowedDevicePolicy:{allowedDeviceClasses:[]}
};
