/* One participant presentation flow for Demo, Preview, and Live. */
(function(root){
  const BASE="/experimentfeed", Q=root.SocyviaQuestionnaires, T=root.SocyviaTelemetry;
  const validPart=value=>/^[a-z0-9][a-z0-9-]{2,80}$/i.test(value||"");
  const localized=(value,language)=>typeof value==="string"?value:(value?.[language]||value?.en||value?.ar||"");
  const copy={
    en:{loading:"Preparing your study",unavailable:"This experiment is currently unavailable",unavailableBody:"Please check the link or contact the researcher who shared this study.",retry:"Try again",information:"Study information",continue:"Continue",consent:"Consent",consentBody:"Please confirm that you have read the study information before continuing.",consentCheck:"I have read the study information and agree to participate.",ready:"Ready to begin",readyBody:"When you choose Start Experiment, the study session and experimental timing will begin.",start:"Start Experiment",starting:"Starting your study",beginFailed:"We could not start the study. Please try again.",recruitmentClosed:"This study is not currently open to new participants.",questionnaireFailed:"The questionnaire is temporarily unavailable. Please try again.",feed:"SOCYVIA Experiment Feed",contentUnavailable:"The study content is temporarily unavailable. Please contact the researcher.",finishFeed:"Finish feed",finish:"Complete study",completion:"Completion",completionBody:"Thank you. Your study flow is complete.",voluntary:"Participation is voluntary. You may stop at any time before completing the study.",privacy:"Your responses are handled according to the study information provided by the researcher.",duration:"Estimated duration",instructions:"Participant instructions",comments:"Comment",writeComment:"Write a comment…",submitComment:"Submit",linkCopied:"Link copied",preview:"Researcher Preview · No research data recorded"},
    ar:{loading:"يتم تحضير الدراسة",unavailable:"هذه التجربة غير متاحة حاليا",unavailableBody:"يرجى التحقق من الرابط أو التواصل مع الباحث الذي شارك هذه الدراسة.",retry:"إعادة المحاولة",information:"معلومات الدراسة",continue:"متابعة",consent:"الموافقة",consentBody:"يرجى تأكيد قراءة معلومات الدراسة قبل المتابعة.",consentCheck:"قرأت معلومات الدراسة وأوافق على المشاركة.",ready:"جاهز للبدء",readyBody:"عند اختيار بدء التجربة، ستبدأ جلسة الدراسة والتوقيت التجريبي.",start:"بدء التجربة",starting:"يتم بدء الدراسة",beginFailed:"تعذر بدء الدراسة. يرجى المحاولة مرة أخرى.",recruitmentClosed:"هذه الدراسة غير مفتوحة حاليا لمشاركين جدد.",questionnaireFailed:"الاستبيان غير متاح مؤقتا. يرجى المحاولة مرة أخرى.",feed:"SOCYVIA Experiment Feed",contentUnavailable:"محتوى الدراسة غير متاح مؤقتا. يرجى التواصل مع الباحث.",finishFeed:"إنهاء المحتوى",finish:"إكمال الدراسة",completion:"الإكمال",completionBody:"شكرا لك. اكتمل مسار الدراسة.",voluntary:"المشاركة طوعية. يمكنك التوقف في أي وقت قبل إكمال الدراسة.",privacy:"تتم معالجة استجاباتك وفقا لمعلومات الدراسة المقدمة من الباحث.",duration:"المدة التقديرية",instructions:"تعليمات المشارك",comments:"تعليق",writeComment:"اكتب تعليقا…",submitComment:"إرسال",linkCopied:"تم نسخ الرابط",preview:"معاينة الباحث · لا يتم تسجيل بيانات بحثية"}
  };
  const responseJson=async response=>{try{return await response.json()}catch{return null}};
  const escape=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
  const field=(value,...names)=>names.map(name=>value?.[name]).find(item=>item!==undefined&&item!==null);
  const objectJson=value=>{try{return typeof value==="string"?JSON.parse(value):value||{}}catch{return {}}};
  const demoPackage=()=>root.SocyviaDemoExperimentPackage||{};
  function demoConfiguration(route){const pkg=demoPackage(),study=pkg.study||{};return normaliseConfiguration({deploymentPublicId:"socyvia-demo",defaultRuntimeLanguage:pkg.defaultRuntimeLanguage||"en",interfaceLanguages:["en","ar"],defaultInterfaceLanguage:pkg.defaultRuntimeLanguage||"en",study:{...study,estimatedDurationMinutes:pkg.estimatedDurationMinutes||4},participantFlow:{preQuestionnaire:!!pkg.questionnaires?.PRE,postQuestionnaire:!!pkg.questionnaires?.POST},researcher:pkg.researcher||{}},route)}
  const demoContent=()=>Array.isArray(demoPackage().orderedStimuli)?demoPackage().orderedStimuli.map(item=>({contentId:item.contentId||item.stimulusId,title:item.title||"",body:item.body||item.bodyText||"",media:item.media,interactions:item.interactions||{like:true,comment:true,readMore:true,save:true,share:true}})):[];
  const demoQuestionnaire=stage=>demoPackage().questionnaires?.[stage]||null;
  function parseRoute(pathname){const raw=String(pathname||""),mounted=raw==="/experimentfeed"||raw.startsWith("/experimentfeed/"),parts=(mounted?raw.replace(/^\/experimentfeed\/?/,""):raw.replace(/^\//,"")).split("/").filter(Boolean);if(parts.length===1&&parts[0]==="demo")return {mode:"demo"};if(mounted&&parts.length===2&&parts[0]==="preview"&&/^[a-f0-9]{24,64}$/i.test(parts[1]))return {mode:"preview",previewTicket:parts[1]};if(!mounted&&parts.length===2&&validPart(parts[0])&&/^\d{8}$/.test(parts[1]))return {mode:"real",researcherHandle:parts[0],experimentCode:parts[1],canonical:true};if(mounted&&parts.length===2&&validPart(parts[0])&&validPart(parts[1]))return {mode:"real",researcherHandle:parts[0],experimentCode:parts[1]};return {mode:"invalid"}}
  function normaliseConfiguration(raw,route){const study=field(raw,"study","Study","studyMetadata","StudyMetadata")||{},metadata=objectJson(field(study,"studyMetadataJson","StudyMetadataJson")),researcher=field(raw,"researcher","Researcher","researcherIdentity","ResearcherIdentity")||field(metadata,"researcher","Researcher")||{},language=field(raw,"defaultRuntimeLanguage","DefaultRuntimeLanguage","language","Language")==="ar"?"ar":"en",expected=field(study,"estimatedDuration","ExpectedSessionDurationMinutes")??field(raw,"estimatedDuration","ExpectedSessionDurationMinutes"),flow=field(raw,"participantFlow","ParticipantFlow")||{};return {deploymentPublicId:String(field(raw,"deploymentPublicId","DeploymentPublicId","publicId","PublicId")||`${route.researcherHandle}-${route.experimentCode}`),language,researcher:{name:field(researcher,"name","Name","researcherName","ResearcherName")||{},role:field(researcher,"role","Role","researcherRole","ResearcherRole")||{},affiliation:field(researcher,"affiliation","Affiliation","researcherAffiliation","ResearcherAffiliation")||{}},study:{title:field(study,"title","Title")||field(raw,"title","Title")||{},description:field(study,"description","Description","purpose","Purpose","studyInformation","StudyInformation")||field(metadata,"description","Description")||{},instructions:field(study,"instructions","Instructions","participantInstructions","ParticipantInstructions")||{},estimatedDuration:expected?{en:`${expected} minutes`,ar:`${expected} دقائق`}:"",privacy:field(study,"privacy","Privacy")||{},consentText:field(study,"consentText","ConsentText")||field(raw,"consentText","ConsentText")||{}},flow:{preQuestionnaire:!!field(flow,"preQuestionnaire","PreQuestionnaire","preMeasureEnabled","PreMeasureEnabled"),postQuestionnaire:!!field(flow,"postQuestionnaire","PostQuestionnaire","postMeasureEnabled","PostMeasureEnabled")},deviceRules:field(raw,"deviceRules","DeviceRules")||{}}}
  function createTelemetryBoundary(session,monotonicNow=()=>performance.now(),utcNow=()=>new Date().toISOString(),eventId=()=>root.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`){const start=monotonicNow();return {record:(eventType,{contentId,payload}={})=>({eventId:eventId(),eventType,contentId,clientTimestampUtc:utcNow(),clientRelativeMilliseconds:Math.max(0,Math.floor(monotonicNow()-start)),payloadJson:payload===undefined?undefined:JSON.stringify(payload),schemaVersion:session.telemetrySchemaVersion||T?.schemaVersion||"SOCYVIA.RemoteTelemetry/2"})}}
  function createParticipantFlow({route,fetcher=root.fetch?.bind(root),monotonicNow=()=>performance.now(),utcNow=()=>new Date().toISOString(),eventId=()=>root.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`}={}){
    let phase="loading",config=null,consented=false,session=null,preIdentity=null,telemetry=null,buffer=null,contentItems=[],contentUnavailable=false,questionnaire=null,questionnaireAnswers={},questionnaireErrors={},notice="",beginPromise=null,completePromise=null,feedEnded=false;
    const interactions=new Map(),expanded=new Set(),comments=new Map(); let impressionTracker=null;
    const snapshot=()=>({phase,config,consented,session,preIdentity,telemetry,contentItems,contentUnavailable,questionnaire,questionnaireAnswers,questionnaireErrors,notice,feedEnded,interactions,expanded,comments,plannedStages:{preQuestionnaire:config?.flow.preQuestionnaire||false,postQuestionnaire:config?.flow.postQuestionnaire||false}});
    const preview=()=>route?.mode==="preview", demo=()=>route?.mode==="demo", readOnly=()=>preview()||demo(), apiBase=()=>route?.canonical?`/${encodeURIComponent(route.researcherHandle)}/${encodeURIComponent(route.experimentCode)}`:BASE, previewBase=()=>`${BASE}/api/preview/${encodeURIComponent(route.previewTicket)}`;
    async function load(){if(!route||!["real","preview","demo"].includes(route.mode)){phase="unavailable";return snapshot()}phase="loading";notice="";try{if(demo()){config=demoConfiguration(route);config.demo=true;config.interfaceLanguages=["en","ar"];phase="information";return snapshot()}const entryUrl=preview()?`${previewBase()}/entry`:`${apiBase()}/api/entry/${encodeURIComponent(route.researcherHandle)}/${encodeURIComponent(route.experimentCode)}`;const response=await fetcher(entryUrl,{headers:{accept:"application/json"}});if(!response?.ok)throw new Error();const raw=await responseJson(response);if(!raw)throw new Error();config=normaliseConfiguration(raw,route);config.preview=preview()&&raw.preview===true;const allowed=Array.isArray(raw.interfaceLanguages)?raw.interfaceLanguages.filter(language=>language==="en"||language==="ar"):[];config.interfaceLanguages=allowed.length?Array.from(new Set(allowed)):[config.language];config.language=raw.defaultInterfaceLanguage==="ar"&&config.interfaceLanguages.includes("ar")?"ar":raw.defaultInterfaceLanguage==="en"&&config.interfaceLanguages.includes("en")?"en":config.interfaceLanguages[0];const minutes=Number(raw.study?.estimatedDurationMinutes);if(Number.isFinite(minutes)&&minutes>0)config.study.estimatedDuration={en:`${minutes} minutes`,ar:`${minutes} دقائق`};phase="information"}catch{phase="unavailable"}return snapshot()}
    function showConsent(){if(phase==="information")phase="consent";return snapshot()}
    function setConsent(value){if(phase==="consent")consented=!!value;return snapshot()}
    function setInterfaceLanguage(language){if(config?.interfaceLanguages?.includes(language))config={...config,language};return snapshot()}
    async function showNextAfterConsent(){if(phase!=="consent"||!consented)return snapshot();if(config?.flow.preQuestionnaire)return loadQuestionnaire("PRE");phase="ready";return snapshot()}
    async function loadQuestionnaire(stage){if(!config)return snapshot();phase=stage==="PRE"?"preQuestionnaire":"postQuestionnaire";notice="";questionnaire=null;questionnaireAnswers={};questionnaireErrors={};try{if(demo()){questionnaire=Q?.normalise(demoQuestionnaire(stage));if(!questionnaire)throw new Error();return snapshot()}const url=preview()?`${previewBase()}/questionnaires/${stage}`:`${apiBase()}/api/questionnaires/${encodeURIComponent(config.deploymentPublicId)}/${stage}`;const response=await fetcher(url,{headers:{accept:"application/json"}});const raw=response?.ok?await responseJson(response):null;questionnaire=Q?.normalise(raw);if(!questionnaire)throw new Error()}catch{notice="questionnaireFailed";phase=stage==="PRE"?"consent":"feed"}return snapshot()}
    async function submitQuestionnaire(answers){if(!questionnaire||!config)return snapshot();questionnaireAnswers=answers||{};questionnaireErrors=Q.validate(questionnaire,questionnaireAnswers);if(Object.keys(questionnaireErrors).length)return snapshot();const stage=questionnaire.stage;if(readOnly()){questionnaire=null;questionnaireAnswers={};if(stage==="PRE")phase="ready";else phase="completion";return snapshot()}try{const body={deploymentPublicId:config.deploymentPublicId,stage,questionnaireVersionId:questionnaire.versionId,responseId:eventId(),responses:questionnaireAnswers};if(stage==="PRE"&&preIdentity){body.participantId=preIdentity.participantId;body.preSessionToken=preIdentity.preSessionToken}if(stage==="POST")body.sessionId=session?.sessionId;const response=await fetcher(`${apiBase()}/api/questionnaires/submit`,{method:"POST",headers:{"content-type":"application/json",accept:"application/json"},body:JSON.stringify(body)});const data=response?.ok?await responseJson(response):null;if(!data?.accepted)throw new Error();if(stage==="PRE"){preIdentity={participantId:data.participantId,preSessionToken:data.preSessionToken};questionnaire=null;questionnaireAnswers={};phase="ready"}else{questionnaire=null;questionnaireAnswers={};await complete()} }catch{notice="questionnaireFailed"}return snapshot()}
    async function begin(){if(phase!=="ready"||!consented||!config)return snapshot();if(beginPromise)return beginPromise;phase="starting";notice="";beginPromise=(async()=>{try{if(readOnly()){if(demo()){contentItems=demoContent();contentUnavailable=false}else{const contentResponse=await fetcher(`${previewBase()}/content`,{headers:{accept:"application/json"}});const content=contentResponse?.ok?await responseJson(contentResponse):null;contentItems=Array.isArray(content?.items)?content.items:[];contentUnavailable=!contentResponse?.ok}phase="feed";return snapshot()}const body={deploymentPublicId:config.deploymentPublicId};if(preIdentity){body.participantId=preIdentity.participantId;body.preSessionToken=preIdentity.preSessionToken}const response=await fetcher(`${apiBase()}/api/begin`,{method:"POST",headers:{"content-type":"application/json",accept:"application/json"},body:JSON.stringify(body)});if(!response?.ok){notice=response?.status===409?"recruitmentClosed":"beginFailed";throw new Error()}const data=await responseJson(response);if(!data?.participantId||!data?.sessionId||!data?.conditionId||!data?.telemetrySchemaVersion)throw new Error();session={participantId:data.participantId,sessionId:data.sessionId,conditionId:data.conditionId,telemetrySchemaVersion:data.telemetrySchemaVersion};telemetry=createTelemetryBoundary(session,monotonicNow,utcNow,eventId);
        const t0=monotonicNow();buffer=T?.createBuffer({sessionId:session.sessionId,monotonicNow:()=>monotonicNow()-t0,utcNow,eventId,schema:session.telemetrySchemaVersion,send:sendEvents});impressionTracker=T?.createQualifiedImpressionTracker({monotonicNow:()=>monotonicNow()-t0,onQualified:(contentId,payload)=>buffer?.record("content_impression",{contentId,payload})});const contentResponse=await fetcher(`${apiBase()}/api/session/${encodeURIComponent(session.sessionId)}/content`,{headers:{accept:"application/json"}});const content=contentResponse?.ok?await responseJson(contentResponse):null;contentItems=Array.isArray(content?.items)?content.items:[];contentUnavailable=!contentResponse?.ok;phase="feed"}catch{notice=notice||"beginFailed";phase="ready"}finally{beginPromise=null}return snapshot()})();return beginPromise}
    async function sendEvents(events){const response=await fetcher(`${apiBase()}/api/events`,{method:"POST",headers:{"content-type":"application/json",accept:"application/json"},body:JSON.stringify({sessionId:session?.sessionId,events})});const data=response?.ok?await responseJson(response):null;if(!data?.acknowledged)throw new Error();return data.acknowledged}
    function record(eventType,contentId,payload){return buffer?.record(eventType,{contentId,payload})||null}
    function toggle(contentId,action){const current=interactions.get(contentId)||{};if(action==="like"){current.like=!current.like;record(current.like?"like":"unlike",contentId)}if(action==="save"){current.save=!current.save;record(current.save?"save":"unsave",contentId)}if(action==="share")record("share",contentId);if(action==="comment"){current.commentOpen=!current.commentOpen;record("comment_open",contentId)}if(action==="readMore"){current.readMore=!current.readMore;expanded[current.readMore?"add":"delete"](contentId);record(current.readMore?"read_more_open":"read_more_close",contentId)}interactions.set(contentId,current);return snapshot()}
    function submitComment(contentId,text){const current=interactions.get(contentId)||{};if(!current.commentOpen||!String(text||"").trim())return snapshot();const item=contentItems.find(value=>value.contentId===contentId),collect=!!item?.interactions?.collectCommentText;record("comment_submit",contentId,collect?{length:String(text).trim().length,text:String(text).trim()}:{length:String(text).trim().length});comments.set(contentId,[...(comments.get(contentId)||[]),{author:"You",text:String(text).trim()}]);return snapshot()}
    async function finishFeed(){if(phase!=="feed"||feedEnded)return snapshot();feedEnded=true;if(!readOnly()){record("experiment_feed_end");await buffer?.flush()}if(config?.flow.postQuestionnaire)await loadQuestionnaire("POST");else if(readOnly())phase="completion";else await complete();return snapshot()}
    async function complete(){if(readOnly()){phase="completion";return snapshot()}if(!session||completePromise||phase==="completion")return snapshot();completePromise=(async()=>{try{await buffer?.flush();const response=await fetcher(`${apiBase()}/api/complete`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId:session.sessionId})});if(!response?.ok)throw new Error();buffer?.close();phase="completion"}catch{notice="beginFailed"}finally{completePromise=null}return snapshot()})();return completePromise}
    return {load,showConsent,setConsent,setInterfaceLanguage,showNextAfterConsent,loadQuestionnaire,submitQuestionnaire,begin,complete,finishFeed,toggle,submitComment,record,snapshot,getImpressionTracker:()=>impressionTracker};
  }
  const languageOf=config=>config?.language==="ar"?"ar":"en",content=(value,lang,fallback="")=>localized(value,lang)||fallback;
  // UI locale is deliberately distinct from stimulus language. This helper is only used
  // for researcher-authored localized instrument metadata, never for a feed stimulus.
  const instrument=(value,lang,fallback="")=>localized(value,lang)||fallback;
  const stimulus=value=>typeof value==="string"?value:(value?.en||value?.ar||"");
  const languageSwitch=(config,lang)=>config?.interfaceLanguages?.length>1?`<div class="participant-language" role="group" aria-label="Language"><button type="button" data-real-language="en" class="${lang==="en"?"active":""}">EN</button><button type="button" data-real-language="ar" class="${lang==="ar"?"active":""}">AR</button></div>`:"";
  function researcherCard(config,lang){const r=config.researcher,name=content(r.name,lang),role=content(r.role,lang),affiliation=content(r.affiliation,lang);if(!name&&!role&&!affiliation)return "";return `<aside class="study-researcher"><span class="researcher-avatar" aria-hidden="true">${escape((name||"R").trim().slice(0,1).toUpperCase())}</span><span><strong>${escape(name)}</strong>${role?`<small>${escape(role)}</small>`:""}${affiliation?`<small>${escape(affiliation)}</small>`:""}</span></aside>`}
  const labels={en:{like:"Like",comment:"Comment",readMore:"Read more",showLess:"Show less",save:"Save",share:"Share"},ar:{like:"إعجاب",comment:"تعليق",readMore:"اقرأ المزيد",showLess:"عرض أقل",save:"حفظ",share:"مشاركة"}};
  function previewMedia(item){const media=item.media;if(!media?.url)return "";const url=escape(media.url),alt=escape(media.alt||item.title||"");if(media.kind==="video")return `<video controls preload="metadata" class="real-preview-media"><source src="${url}"></video>`;if(media.kind==="audio")return `<audio controls preload="metadata" class="real-preview-media"><source src="${url}"></audio>`;if(media.kind==="external")return `<section class="source-card real-external-source"><div><span>External source</span><strong>${alt||"Study source"}</strong><a class="source-action" href="${url}" target="_blank" rel="noopener noreferrer">Open source</a></div></section>`;return `<img class="real-preview-media" src="${url}" alt="${alt}">`}
  function textPost(item,state,lang){
    const shell=root.SocyviaParticipantFeedShell,selected=state.interactions.get(item.contentId)||{},available=Object.entries(item.interactions||{}).filter(([name,enabled])=>enabled&&labels[lang][name]),open=!!selected.commentOpen,localComments=state.comments.get(item.contentId)||[];
    const header=`<header class="post-head"><span class="avatar brand-avatar" aria-hidden="true"><img src="${BASE}/demo-media/socyvia-mark.png" alt=""></span><div class="person"><strong>SOCYVIA</strong><span>Experiment Feed</span></div></header>`;
    const postCopy=`<div class="post-copy">${item.title?`<h2 class="real-post-title">${escape(stimulus(item.title))}</h2>`:""}<p class="post-text real-post-body ${selected.readMore?"expanded":"is-clamped"}">${escape(stimulus(item.body))}</p></div>`;
    const toolbar=available.length?`<div class="toolbar real-post-actions" style="--action-count:${Math.max(1,available.length)}">${available.map(([name])=>{const active=name==="comment"?selected.commentOpen:selected[name],label=name==="readMore"&&selected.readMore?labels[lang].showLess:labels[lang][name];return `<button type="button" data-real-post-action="${name}" data-content-id="${escape(item.contentId)}" class="${active?"active":""}" ${name==="readMore"?`aria-expanded="${selected.readMore?"true":"false"}"`:""}>${shell?.icon(name)||""}<span>${label}</span></button>`}).join("")}</div>`:"";
    const comments=open?`<section class="comments real-comments"><form data-real-comment-form data-content-id="${escape(item.contentId)}"><label><span class="sr-only">${labels[lang].comment}</span><input name="comment" maxlength="1000" placeholder="${copy[lang].writeComment}" required></label><button type="submit">${copy[lang].submitComment}</button></form>${localComments.map(comment=>`<div class="comment-item"><span class="comment-avatar">Y</span><div><strong>${escape(comment.author)}</strong><p>${escape(comment.text)}</p></div></div>`).join("")}</section>`:"";
    if(!shell)return `<article class="post real-text-post" data-real-content-id="${escape(item.contentId)}">${header}${postCopy}${previewMedia(item)}${toolbar}${comments}</article>`;
    return shell.article({attributes:`data-real-content-id="${escape(item.contentId)}"`,header,copy:postCopy,media:previewMedia(item),toolbar,comments});
  }
  function layout(flow){const state=flow.snapshot(),config=state.config,lang=languageOf(config),t=key=>copy[lang][key],study=config?.study||{},title=instrument(study.title,lang,t("information")),description=instrument(study.description,lang),instructions=instrument(study.instructions,lang),consentText=instrument(study.consentText,lang,t("consentCheck"));document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";const modeBadge=config?.demo?`<span class="preview-mode-badge feed-notice">${lang==="ar"?"عرض توضيحي اصطناعي · لا يتم تسجيل بيانات بحثية":"Synthetic Demo · No research data recorded"}</span>`:config?.preview?`<span class="preview-mode-badge feed-notice">${t("preview")}</span>`:`<span class="preview-mode-badge feed-notice">${lang==="ar"?"دراسة منشورة · يتم تسجيل بيانات البحث":"Published study · Research data are recorded"}</span>`;const header=config?`<header class="feed-header real-header"><a class="brand" href="${BASE}"><img src="${BASE}/demo-media/socyvia-mark.png" alt="SOCYVIA"><span><strong>SOCYVIA</strong><b>Experiment Feed</b></span></a>${researcherCard(config,lang)}${modeBadge}${languageSwitch(config,lang)}</header>`:"";let body="";
    if(state.phase==="loading"||state.phase==="starting")body=`<section class="experiment-state loading-state" aria-live="polite"><span class="state-orb"></span><h1>${t(state.phase)}</h1></section>`;
    else if(state.phase==="unavailable")body=`<section class="experiment-state"><img src="${BASE}/demo-media/socyvia-mark.png" alt="SOCYVIA"><h1>${t("unavailable")}</h1><p>${t("unavailableBody")}</p><button class="primary" data-real-action="retry">${t("retry")}</button></section>`;
    else if(state.phase==="information")body=`<section class="experiment-state study-information"><p class="eyebrow">SOCYVIA Experiment Feed</p><h1>${escape(title)}</h1>${description?`<p class="study-description">${escape(description)}</p>`:""}${study.estimatedDuration?`<p class="study-detail"><b>${t("duration")}</b> ${escape(content(study.estimatedDuration,lang,study.estimatedDuration))}</p>`:""}${instructions?`<section class="study-copy"><h2>${t("instructions")}</h2><p>${escape(instructions)}</p></section>`:""}<section class="study-copy"><p>${t("voluntary")}</p><p>${content(study.privacy,lang,t("privacy"))}</p></section><button class="primary" data-real-action="consent">${t("continue")}</button></section>`;
    else if(state.phase==="consent")body=`<section class="experiment-state consent-state"><p class="eyebrow">SOCYVIA Experiment Feed</p><h1>${t("consent")}</h1><p>${t("consentBody")}</p><label class="consent-control"><input type="checkbox" data-real-consent ${state.consented?"checked":""}><span>${escape(consentText)}</span></label>${state.notice?`<p class="session-error" role="alert">${t(state.notice)}</p>`:""}<button class="primary" data-real-action="next-after-consent" ${state.consented?"":"disabled"}>${t("continue")}</button></section>`;
    else if(state.phase==="preQuestionnaire"||state.phase==="postQuestionnaire")body=state.questionnaire?`<section class="questionnaire-state">${Q.render(state.questionnaire,lang,state.questionnaireAnswers,state.questionnaireErrors)}</section>`:`<section class="experiment-state"><h1>${t("questionnaireFailed")}</h1><button class="primary" data-real-action="retry-questionnaire">${t("retry")}</button></section>`;
    else if(state.phase==="ready")body=`<section class="experiment-state ready-state"><p class="eyebrow">SOCYVIA Experiment Feed</p><h1>${t("ready")}</h1><p>${t("readyBody")}</p>${state.notice?`<p class="session-error" role="alert">${t(state.notice)}</p>`:""}<button class="primary" data-real-action="begin">${t("start")}</button></section>`;
    else if(state.phase==="feed")body=`<main class="feed real-feed" data-socyvia-feed-shell="${root.SocyviaParticipantFeedShell?.version||"SOCYVIA.RichFeed/1"}"><section class="real-feed-intro"><p class="eyebrow">${t("feed")}</p><h1>${escape(title)}</h1></section>${state.contentUnavailable?`<section class="real-feed-placeholder"><p>${t("contentUnavailable")}</p></section>`:state.contentItems.map(item=>textPost(item,state,lang)).join("")}<section class="real-feed-placeholder"><button class="primary" data-real-action="feed-end" ${state.feedEnded?"disabled":""}>${t("finishFeed")}</button></section></main>`;
    else body=`<section class="experiment-state"><h1>${t("completion")}</h1><p>${t("completionBody")}</p></section>`;
    document.querySelector("#app").innerHTML=`<div class="real-experiment-shell">${header}<main class="experiment-main">${body}</main></div>`;
  }
  function bindImpressions(flow){const tracker=flow.getImpressionTracker();if(!tracker||!root.IntersectionObserver)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{const contentId=entry.target.dataset.realContentId;if(entry.isIntersecting)tracker.enter(contentId,entry.intersectionRatio);else tracker.exit(contentId)}),{threshold:[0,T?.impressionRule?.visibilityThreshold||.6]});document.querySelectorAll("[data-real-content-id]").forEach(item=>observer.observe(item));}
  function configureReadMore(){document.querySelectorAll("button[data-real-post-action='readMore']").forEach(button=>{const post=button.closest(".real-text-post"),body=post?.querySelector(".real-post-body"),expanded=body?.classList.contains("expanded");button.hidden=!!body&&!expanded&&body.scrollHeight<=body.clientHeight+1})}
  function start(){const route=parseRoute(location.pathname);if(!["real","preview","demo"].includes(route.mode))return false;const flow=createParticipantFlow({route}),render=()=>{layout(flow);configureReadMore();if(route.mode==="real")bindImpressions(flow)};document.addEventListener("click",async event=>{const language=event.target.closest("[data-real-language]");if(language){flow.setInterfaceLanguage(language.dataset.realLanguage);render();return}const button=event.target.closest("[data-real-action]");if(button){const action=button.dataset.realAction;if(action==="retry")await flow.load();else if(action==="consent")flow.showConsent();else if(action==="next-after-consent")await flow.showNextAfterConsent();else if(action==="begin")await flow.begin();else if(action==="feed-end")await flow.finishFeed();else if(action==="retry-questionnaire")await flow.loadQuestionnaire(flow.snapshot().phase==="preQuestionnaire"?"PRE":"POST");render();return}const post=event.target.closest("[data-real-post-action]");if(post){flow.toggle(post.dataset.contentId,post.dataset.realPostAction);render()}});document.addEventListener("change",event=>{if(event.target.matches?.("[data-real-consent]")){flow.setConsent(event.target.checked);render()}});document.addEventListener("submit",async event=>{const form=event.target;if(form.matches?.("[data-questionnaire-stage]")){event.preventDefault();await flow.submitQuestionnaire(Q.values(form,flow.snapshot().questionnaire));render()}if(form.matches?.("[data-real-comment-form]")){event.preventDefault();flow.submitComment(form.dataset.contentId,new FormData(form).get("comment"));render()}});render();flow.load().then(render);return true}
  const api={parseRoute,normaliseConfiguration,createParticipantFlow,createTelemetryBoundary,start};root.SocyviaParticipantFlow=api;if(typeof module!=="undefined"&&module.exports)module.exports=api;
})(typeof window!=="undefined"?window:globalThis);
