/* Controlled behavioral telemetry. It is instantiated only after a successful real begin/T0. */
(function(root){
  const schemaVersion="SOCYVIA.RemoteTelemetry/2";
  const allowed=new Set(["content_impression","content_open","content_close","read_more_open","read_more_close","like","unlike","comment_open","comment_submit","save","unsave","share","feed_next","feed_previous","experiment_feed_end"]);
  const impressionRule=Object.freeze({version:"SOCYVIA.Impression/1",visibilityThreshold:0.6,minimumVisibleMs:1000,repeatPolicy:"first-qualified-per-content-per-session"});
  const stableId=()=>root.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
  function createBuffer({sessionId,monotonicNow=()=>performance.now(),utcNow=()=>new Date().toISOString(),send,batchSize=20,eventId=stableId,schema=schemaVersion}={}){
    let queue=[],flushing=null,closed=false;
    function record(eventType,{contentId,payload}={}){if(closed||!allowed.has(eventType))return null;const event={eventId:eventId(),eventType,contentId:contentId||undefined,clientTimestampUtc:utcNow(),clientRelativeMilliseconds:Math.max(0,Math.floor(monotonicNow())),payloadJson:payload===undefined?undefined:JSON.stringify(payload),schemaVersion:schema};queue.push(event);if(queue.length>=batchSize)void flush();return event}
    async function flush(){if(flushing||!queue.length||typeof send!=="function")return flushing||false;const batch=queue.slice(0,batchSize);flushing=(async()=>{try{const acknowledged=await send(batch);const accepted=new Set(Array.isArray(acknowledged)?acknowledged:[]);if(accepted.size)queue=queue.filter(event=>!accepted.has(event.eventId));return accepted.size===batch.length}catch{return false}finally{flushing=null}})();return flushing}
    return {record,flush,pending:()=>queue.slice(),close:()=>{closed=true}};
  }
  function createQualifiedImpressionTracker({rule=impressionRule,monotonicNow=()=>performance.now(),onQualified,setTimer=root.setTimeout,clearTimer=root.clearTimeout}={}){const visible=new Map(),qualified=new Set();function qualify(contentId){const state=visible.get(contentId);if(!state||qualified.has(contentId))return false;const elapsed=Math.max(0,Math.floor(monotonicNow()-state.started));if(elapsed<rule.minimumVisibleMs)return false;qualified.add(contentId);clearTimer?.(state.timer);onQualified?.(contentId,{visibilityThreshold:rule.visibilityThreshold,qualifiedVisibleMs:elapsed,ruleVersion:rule.version});return true}function enter(contentId,ratio){if(qualified.has(contentId)||ratio<rule.visibilityThreshold||visible.has(contentId))return;const started=monotonicNow(),timer=setTimer?.(()=>qualify(contentId),rule.minimumVisibleMs);visible.set(contentId,{started,timer})}function exit(contentId){const state=visible.get(contentId);visible.delete(contentId);if(!state)return false;clearTimer?.(state.timer);if(qualified.has(contentId))return false;const elapsed=Math.max(0,Math.floor(monotonicNow()-state.started));if(elapsed<rule.minimumVisibleMs)return false;qualified.add(contentId);onQualified?.(contentId,{visibilityThreshold:rule.visibilityThreshold,qualifiedVisibleMs:elapsed,ruleVersion:rule.version});return true}function settle(contentId){return qualify(contentId)}return {enter,exit,settle,qualified:contentId=>qualified.has(contentId)}}
  const api={schemaVersion,allowed,impressionRule,createBuffer,createQualifiedImpressionTracker};root.SocyviaTelemetry=api;if(typeof module!=="undefined"&&module.exports)module.exports=api;
})(typeof window!=="undefined"?window:globalThis);
