using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Data.Sqlite;
using SOCYVIA.Data;
using SOCYVIA.Models;
using SOCYVIA.Repositories;

namespace SOCYVIA.Services;

public static class DemoScientificDataService
{
    public const int GeneratorSeed = 20260817;
    public const string GeneratorVersion = "SOCYVIA.DEMO-SCIENCE/3";

    public static IReadOnlyList<double> GenerateValidationSequence(int seed, int count)
    {
        if (count < 0) throw new ArgumentOutOfRangeException(nameof(count));
        var random = new Random(seed);
        return Enumerable.Range(0, count).Select(_ => Normal(random)).ToArray();
    }

    public static async Task EnsureAsync(string studyId)
    {
        await using var connection=await DatabaseService.OpenConnectionAsync();
        var groups=await IdsAsync(connection,"SELECT Id FROM Groups WHERE StudyId=$study ORDER BY SortOrder;",studyId);
        var conditions=await IdsAsync(connection,"SELECT Id FROM ExperimentalConditions WHERE StudyId=$study ORDER BY SortOrder;",studyId);
        var content=await IdsAsync(connection,"SELECT ContentItemId FROM ExperimentalFeedItems WHERE FeedId=(SELECT Id FROM ExperimentalFeeds WHERE StudyId=$study ORDER BY SortOrder LIMIT 1) ORDER BY SortOrder;",studyId);
        if(groups.Count!=3||conditions.Count!=3||content.Count<10)throw new InvalidOperationException("The guided Demo foundation is incomplete.");
        await using var transaction=connection.BeginTransaction();
        try
        {
            var questionnaireId=Stable(studyId,"questionnaire");var versionId=Stable(studyId,"questionnaire-version-1");var sectionId=Stable(studyId,"questionnaire-section");var assignmentId=Stable(studyId,"questionnaire-assignment-post");var scaleId=Stable(studyId,"questionnaire-scale");
            await Execute(connection,transaction,"UPDATE Studies SET UsesQuestionnaires=1, TargetSampleSize=60, MetadataJson=json_set(COALESCE(MetadataJson,'{}'),'$.SyntheticGeneratorVersion',$version,'$.SyntheticGeneratorSeed',$seed) WHERE Id=$study;",p=>{p.AddWithValue("$study",studyId);p.AddWithValue("$version",GeneratorVersion);p.AddWithValue("$seed",GeneratorSeed);});
            await Execute(connection,transaction,"INSERT OR IGNORE INTO Questionnaires (Id,StudyId,Title,Description,SortOrder,CreatedAtUtc,UpdatedAtUtc,IsActive,CurrentVersionId,InstrumentType,MetadataJson) VALUES ($id,$study,'SOCYVIA Demo Questionnaire','Illustrative instrument; not validated; synthetic/demo use only.',0,$now,$now,1,$version,'CUSTOM',$metadata);",p=>{p.AddWithValue("$id",questionnaireId);p.AddWithValue("$study",studyId);p.AddWithValue("$version",versionId);p.AddWithValue("$now",Utc(0));p.AddWithValue("$metadata",JsonSerializer.Serialize(new{IsDemo=true,IsSynthetic=true,IsValidated=false,Notice="Illustrative instrument only"}));});
            await Execute(connection,transaction,"INSERT OR IGNORE INTO QuestionnaireVersions (Id,QuestionnaireId,VersionNumber,VersionLabel,Status,Language,InstrumentType,Construct,Citation,LicenseStatus,RedistributionStatus,ValidationNotes,ScoringAvailability,SchemaHash,IsImmutable,CreatedAtUtc,PublishedAtUtc) VALUES ($id,$questionnaire,1,'Demo version 1','Published','en','CUSTOM','Perceived engagement-cue response',NULL,'CUSTOM','USER_PROVIDED','SOCYVIA-created illustrative items; not psychometrically validated.','MEAN composite for software demonstration',$hash,1,$now,$now);",p=>{p.AddWithValue("$id",versionId);p.AddWithValue("$questionnaire",questionnaireId);p.AddWithValue("$hash",Stable(studyId,"questionnaire-schema-hash"));p.AddWithValue("$now",Utc(0));});
            await Execute(connection,transaction,"INSERT OR IGNORE INTO QuestionnaireSections (Id,QuestionnaireVersionId,Title,Description,SortOrder) VALUES ($id,$version,'Post-experiment perceptions','Synthetic demonstration items',0);",p=>{p.AddWithValue("$id",sectionId);p.AddWithValue("$version",versionId);});
            var itemTexts=new[]{"The engagement indicators were noticeable","The content appeared to have social consensus","I paid attention to engagement cues","Engagement indicators did not affect my attention","I would consider interacting with this content"};
            var itemVariables=new[]{"engagement_salience","perceived_consensus","cue_attention","cue_ignored_reverse","interaction_intention"};
            var questionIds=new string[5];
            for(var item=0;item<5;item++)
            {
                questionIds[item]=Stable(studyId,"question",item.ToString());
                await Execute(connection,transaction,"INSERT OR IGNORE INTO QuestionnaireItems (Id,QuestionnaireVersionId,SectionId,VariableName,QuestionText,QuestionType,MeasurementLevel,IsRequired,SortOrder,ConfigurationJson) VALUES ($id,$version,$section,$variable,$text,'LIKERT','ORDINAL',1,$sort,$configuration);",p=>{p.AddWithValue("$id",questionIds[item]);p.AddWithValue("$version",versionId);p.AddWithValue("$section",sectionId);p.AddWithValue("$variable",itemVariables[item]);p.AddWithValue("$text",itemTexts[item]);p.AddWithValue("$sort",item);p.AddWithValue("$configuration",JsonSerializer.Serialize(new{Minimum=1,Maximum=5,Ordered=true}));});
                for(var option=1;option<=5;option++)await Execute(connection,transaction,"INSERT OR IGNORE INTO QuestionOptions (Id,QuestionId,ValueCode,NumericCode,DisplayLabel,SortOrder) VALUES ($id,$question,$code,$numeric,$label,$sort);",p=>{p.AddWithValue("$id",Stable(questionIds[item],"option",option.ToString()));p.AddWithValue("$question",questionIds[item]);p.AddWithValue("$code",option.ToString());p.AddWithValue("$numeric",option);p.AddWithValue("$label",option switch{1=>"Strongly disagree",2=>"Disagree",3=>"Neither agree nor disagree",4=>"Agree",_=>"Strongly agree"});p.AddWithValue("$sort",option-1);});
            }
            await Execute(connection,transaction,"INSERT OR IGNORE INTO QuestionnaireScales (Id,QuestionnaireVersionId,Name,VariableName,ScoringMethod,MissingItemRule,MinimumAnsweredItems) VALUES ($id,$version,'Engagement cue response','engagement_cue_response','MEAN','REQUIRE_MINIMUM',4);",p=>{p.AddWithValue("$id",scaleId);p.AddWithValue("$version",versionId);});
            for(var item=0;item<5;item++)await Execute(connection,transaction,"INSERT OR IGNORE INTO QuestionnaireScaleItems (Id,ScaleId,QuestionId,IsReverseCoded,ReverseMinimum,ReverseMaximum,Weight) VALUES ($id,$scale,$question,$reverse,$minimum,$maximum,1);",p=>{p.AddWithValue("$id",Stable(scaleId,"item",item.ToString()));p.AddWithValue("$scale",scaleId);p.AddWithValue("$question",questionIds[item]);p.AddWithValue("$reverse",item==3?1:0);p.AddWithValue("$minimum",item==3?1:DBNull.Value);p.AddWithValue("$maximum",item==3?5:DBNull.Value);});
            await Execute(connection,transaction,"INSERT OR IGNORE INTO QuestionnaireAssignments (Id,StudyId,QuestionnaireVersionId,Placement,SortOrder,IsRequired,IsActive,CreatedAtUtc) VALUES ($id,$study,$version,'POST_EXPERIMENT',0,1,1,$now);",p=>{p.AddWithValue("$id",assignmentId);p.AddWithValue("$study",studyId);p.AddWithValue("$version",versionId);p.AddWithValue("$now",Utc(0));});

            var random=new Random(GeneratorSeed);
            for(var groupIndex=0;groupIndex<3;groupIndex++)for(var participantIndex=1;participantIndex<=20;participantIndex++)
            {
                var code=$"DEMO-{(char)('A'+groupIndex)}{participantIndex:00}";
                var participantId=await ParticipantIdAsync(connection,transaction,studyId,code)??Stable(studyId,"participant",groupIndex.ToString(),participantIndex.ToString());
                var start=new DateTime(2026,8,1+groupIndex,9,0,0,DateTimeKind.Utc).AddMinutes(participantIndex*23);
                var duration=(long)Math.Round(Math.Clamp(245000+groupIndex*18000+Normal(random)*42000,135000,420000));
                await Execute(connection,transaction,"INSERT INTO Participants (Id,StudyId,GroupId,ParticipantCode,Status,IsEligible,ConsentAccepted,ConsentAcceptedAtUtc,HasStartedStudy,HasCompletedStudy,StudyStartedAtUtc,StudyCompletedAtUtc,IsExcluded,HasWithdrawn,ResearcherNotes,MetadataJson,CreatedAtUtc,UpdatedAtUtc) VALUES ($id,$study,$group,$code,'Completed',1,1,$start,1,1,$start,$completed,0,0,'Fictional synthetic participant',$metadata,$start,$completed) ON CONFLICT(StudyId,ParticipantCode) DO UPDATE SET Status='Completed',GroupId=excluded.GroupId,HasStartedStudy=1,HasCompletedStudy=1,StudyStartedAtUtc=excluded.StudyStartedAtUtc,StudyCompletedAtUtc=excluded.StudyCompletedAtUtc,MetadataJson=excluded.MetadataJson;",p=>{p.AddWithValue("$id",participantId);p.AddWithValue("$study",studyId);p.AddWithValue("$group",groups[groupIndex]);p.AddWithValue("$code",code);p.AddWithValue("$start",start.ToString("O"));p.AddWithValue("$completed",start.AddMilliseconds(duration).ToString("O"));p.AddWithValue("$metadata",JsonSerializer.Serialize(new{IsDemo=true,IsSynthetic=true,GeneratorVersion,GeneratorSeed}));});
                participantId=await ParticipantIdAsync(connection,transaction,studyId,code)??participantId;
                await Execute(connection,transaction,"INSERT INTO ParticipantAssignments (Id,StudyId,ParticipantId,GroupId,AssignmentMethod,RandomizationSeed,AssignmentOrder,IsActive,AssignedAtUtc,Notes) SELECT $id,$study,$participant,$group,'Demo',$seed,$order,1,$start,'Synthetic balanced assignment' WHERE NOT EXISTS (SELECT 1 FROM ParticipantAssignments WHERE ParticipantId=$participant AND IsActive=1);",p=>{p.AddWithValue("$id",Stable(studyId,"group-assignment",participantId));p.AddWithValue("$study",studyId);p.AddWithValue("$participant",participantId);p.AddWithValue("$group",groups[groupIndex]);p.AddWithValue("$seed",GeneratorSeed);p.AddWithValue("$order",groupIndex*20+participantIndex);p.AddWithValue("$start",start.ToString("O"));});
                await Execute(connection,transaction,"INSERT OR IGNORE INTO ParticipantConditionAssignments (Id,StudyId,ParticipantId,ConditionId,AssignmentMethod,RandomizationSeed,AssignmentMetadataJson,AssignedAtUtc,IsActive) VALUES ($id,$study,$participant,$condition,'BalancedRandom',$seed,$metadata,$start,1);",p=>{p.AddWithValue("$id",Stable(studyId,"condition-assignment",participantId));p.AddWithValue("$study",studyId);p.AddWithValue("$participant",participantId);p.AddWithValue("$condition",conditions[groupIndex]);p.AddWithValue("$seed",GeneratorSeed);p.AddWithValue("$metadata",JsonSerializer.Serialize(new{IsDemo=true,IsSynthetic=true}));p.AddWithValue("$start",start.ToString("O"));});
                var sessionId=Stable(studyId,"session",participantId);
                await Execute(connection,transaction,"INSERT OR IGNORE INTO Sessions (Id,StudyId,ParticipantId,GroupId,ConditionId,ConfigurationSnapshotId,CreatedAtUtc,LifecycleUpdatedAtUtc,StartedAtUtc,ActualStartedAtUtc,CompletedAtUtc,Status,LifecycleVersion,DurationMilliseconds,CurrentStimulusIndex,CompletedStimulusCount,DeviceName,OperatingSystem,EegEnabled,GsrEnabled,WasInterrupted,MetadataJson) VALUES ($id,$study,$participant,$group,$condition,NULL,$created,$completed,$created,$created,$completed,'Completed',2,$duration,10,10,'SOCYVIA Synthetic Runtime','.NET cross-platform demo',0,0,0,$metadata);",p=>{p.AddWithValue("$id",sessionId);p.AddWithValue("$study",studyId);p.AddWithValue("$participant",participantId);p.AddWithValue("$group",groups[groupIndex]);p.AddWithValue("$condition",conditions[groupIndex]);p.AddWithValue("$created",start.ToString("O"));p.AddWithValue("$completed",start.AddMilliseconds(duration).ToString("O"));p.AddWithValue("$duration",duration);p.AddWithValue("$metadata",JsonSerializer.Serialize(new{IsDemo=true,IsSynthetic=true,GeneratorVersion,GeneratorSeed}));});
                await InsertEvents(connection,transaction,studyId,sessionId,participantId,groups[groupIndex],content,groupIndex,start,duration,random);
                var responseSetId=Stable(studyId,"questionnaire-response",participantId);
                await Execute(connection,transaction,"INSERT OR IGNORE INTO QuestionnaireResponseSets (Id,AssignmentId,StudyId,SessionId,ParticipantId,QuestionnaireId,QuestionnaireVersionId,StartedAtUtc,CompletedAtUtc,DurationMilliseconds,Status,IsDemo,MetadataJson) VALUES ($id,$assignment,$study,$session,$participant,$questionnaire,$version,$started,$completed,$duration,'Completed',1,$metadata);",p=>{p.AddWithValue("$id",responseSetId);p.AddWithValue("$assignment",assignmentId);p.AddWithValue("$study",studyId);p.AddWithValue("$session",sessionId);p.AddWithValue("$participant",participantId);p.AddWithValue("$questionnaire",questionnaireId);p.AddWithValue("$version",versionId);p.AddWithValue("$started",start.AddMilliseconds(duration+5000).ToString("O"));p.AddWithValue("$completed",start.AddMilliseconds(duration+65000).ToString("O"));p.AddWithValue("$duration",60000);p.AddWithValue("$metadata",JsonSerializer.Serialize(new{IsDemo=true,IsSynthetic=true,GeneratorVersion,GeneratorSeed}));});
                var groupMeans=new[]{3.25,2.85,3.60};
                var participantTrait=groupMeans[groupIndex]+Normal(random)*0.90;
                for(var item=0;item<5;item++)
                {
                    var latent=participantTrait+Normal(random)*0.58+(item-2)*0.06;
                    var value=(int)Math.Clamp(Math.Round(latent),1,5);if(item==3)value=6-value;
                    await Execute(connection,transaction,"INSERT INTO QuestionResponseValues (Id,ResponseSetId,QuestionId,RawValue,NumericValue,SelectedOptionIdsJson,RespondedAtUtc) VALUES ($id,$response,$question,$raw,$numeric,$selected,$time) ON CONFLICT(Id) DO UPDATE SET RawValue=excluded.RawValue,NumericValue=excluded.NumericValue,SelectedOptionIdsJson=excluded.SelectedOptionIdsJson,RespondedAtUtc=excluded.RespondedAtUtc;",p=>{p.AddWithValue("$id",Stable(responseSetId,"answer",item.ToString()));p.AddWithValue("$response",responseSetId);p.AddWithValue("$question",questionIds[item]);p.AddWithValue("$raw",value.ToString());p.AddWithValue("$numeric",value);p.AddWithValue("$selected",JsonSerializer.Serialize(new[]{Stable(questionIds[item],"option",value.ToString())}));p.AddWithValue("$time",start.AddMilliseconds(duration+10000+item*9000).ToString("O"));});
                }
                await Classify(connection,transaction,"Participant",participantId,studyId,start);await Classify(connection,transaction,"Session",sessionId,studyId,start);await Classify(connection,transaction,"QuestionnaireResponse",responseSetId,studyId,start);
            }
            // A fixed, deliberately incomplete cohort makes the demo's attrition and
            // eligibility surfaces meaningful without affecting the completed analytic sample.
            for (var dropoutIndex = 0; dropoutIndex < 3; dropoutIndex++)
            {
                var groupId = groups[dropoutIndex];
                var conditionId = conditions[dropoutIndex];
                var code = $"DEMO-I{dropoutIndex + 1:00}";
                var participantId = Stable(studyId, "incomplete-participant", dropoutIndex.ToString());
                var start = new DateTime(2026, 8, 9, 10, 0, 0, DateTimeKind.Utc).AddMinutes(dropoutIndex * 31);
                var sessionId = Stable(studyId, "incomplete-session", dropoutIndex.ToString());
                var metadata = JsonSerializer.Serialize(new { IsDemo = true, IsSynthetic = true, GeneratorVersion, GeneratorSeed, Lifecycle = "FEED_IN_PROGRESS" });
                await Execute(connection, transaction, "INSERT OR IGNORE INTO Participants (Id,StudyId,GroupId,ParticipantCode,Status,IsEligible,ConsentAccepted,ConsentAcceptedAtUtc,HasStartedStudy,HasCompletedStudy,StudyStartedAtUtc,StudyCompletedAtUtc,IsExcluded,HasWithdrawn,ResearcherNotes,MetadataJson,CreatedAtUtc,UpdatedAtUtc) VALUES ($id,$study,$group,$code,'Incomplete',1,1,$start,1,0,$start,NULL,0,0,'Fictional synthetic incomplete participant',$metadata,$start,$start);", p => { p.AddWithValue("$id", participantId); p.AddWithValue("$study", studyId); p.AddWithValue("$group", groupId); p.AddWithValue("$code", code); p.AddWithValue("$start", start.ToString("O")); p.AddWithValue("$metadata", metadata); });
                await Execute(connection, transaction, "INSERT OR IGNORE INTO Sessions (Id,StudyId,ParticipantId,GroupId,ConditionId,ConfigurationSnapshotId,CreatedAtUtc,LifecycleUpdatedAtUtc,StartedAtUtc,ActualStartedAtUtc,CompletedAtUtc,Status,LifecycleVersion,DurationMilliseconds,CurrentStimulusIndex,CompletedStimulusCount,DeviceName,OperatingSystem,EegEnabled,GsrEnabled,WasInterrupted,MetadataJson) VALUES ($id,$study,$participant,$group,$condition,NULL,$start,$start,$start,$start,NULL,'Incomplete',2,60000,3,3,'SOCYVIA Synthetic Runtime','.NET cross-platform demo',0,0,1,$metadata);", p => { p.AddWithValue("$id", sessionId); p.AddWithValue("$study", studyId); p.AddWithValue("$participant", participantId); p.AddWithValue("$group", groupId); p.AddWithValue("$condition", conditionId); p.AddWithValue("$start", start.ToString("O")); p.AddWithValue("$metadata", metadata); });
                await Classify(connection, transaction, "Participant", participantId, studyId, start);
                await Classify(connection, transaction, "Session", sessionId, studyId, start);
            }
            await transaction.CommitAsync();
        }
        catch{await transaction.RollbackAsync();throw;}
        await EnsureComputedAnalysisAsync(studyId);
    }

    public static async Task<(AnalysisDataset Dataset,DataQualityResult Quality,AnalysisSpecification Specification,AnalysisExecution Execution)> EnsureComputedAnalysisAsync(string studyId)
    {
        var dataset=await AnalysisDatasetService.BuildParticipantDatasetAsync(studyId,true);var quality=DataQualityService.Evaluate(dataset);var outcome=dataset.Variables.First(item=>item.Source=="QUESTIONNAIRE_SCALE");var specificationId=Stable(studyId,"analysis","engagement-scale-anova");var specification=new AnalysisSpecification{Id=specificationId,StudyId=studyId,Name="Demo group comparison: engagement cue response",ResearchQuestion="Do synthetic engagement-cue response scores differ across the three demonstration conditions?",Classification=AnalysisClassifications.Exploratory,OutcomeVariableId=outcome.Id,PredictorVariableId="condition",AnalysisFamily="MULTIPLE_INDEPENDENT_GROUPS",Method="ONE_WAY_ANOVA",ConfidenceLevel=0.95,MissingDataHandling="COMPLETE_CASE",MultipleComparisonMethod="HOLM",IsDemo=true,CreatedAtUtc=new DateTime(2026,8,17,0,0,0,DateTimeKind.Utc),UpdatedAtUtc=new DateTime(2026,8,17,0,0,0,DateTimeKind.Utc)};await AnalysisRepository.SaveSpecificationAsync(specification);var latest=await AnalysisRepository.GetLatestExecutionAsync(specificationId);if(latest is not null&&latest.DatasetHash==dataset.DatasetHash&&latest.Status==AnalysisStatuses.Computed)return(dataset,quality,specification,latest);var execution=await ScientificAnalysisEngine.ExecuteAsync(dataset,specification);execution.Id=Stable(specificationId,"execution",dataset.DatasetHash);await AnalysisRepository.SaveExecutionAsync(execution,dataset.Exclusions);return(dataset,quality,specification,execution);
    }

    private static async Task InsertEvents(SqliteConnection c,SqliteTransaction t,string study,string session,string participant,string group,IReadOnlyList<string> content,int groupIndex,DateTime start,long duration,Random random)
    {
        var sequence=1;await Event(c,t,study,session,participant,group,null,CanonicalInteractionEventTypes.SessionStarted,start,0,null,sequence++);await Event(c,t,study,session,participant,group,null,CanonicalInteractionEventTypes.FeedOpened,start.AddMilliseconds(150),150,null,sequence++);long elapsed=1000;for(var index=0;index<content.Count;index++){var dwell=(long)Math.Round(Math.Clamp(15500+groupIndex*1800+Normal(random)*5500,4500,34000));await Event(c,t,study,session,participant,group,content[index],CanonicalInteractionEventTypes.ContentEnteredViewport,start.AddMilliseconds(elapsed),elapsed,null,sequence++);await Event(c,t,study,session,participant,group,content[index],CanonicalInteractionEventTypes.ContentMeaningfullyExposed,start.AddMilliseconds(elapsed+650),elapsed+650,null,sequence++);if(random.NextDouble()<new[]{0.34,0.20,0.45}[groupIndex])await Event(c,t,study,session,participant,group,content[index],CanonicalInteractionEventTypes.PostOpened,start.AddMilliseconds(elapsed+dwell/3),elapsed+dwell/3,null,sequence++);if(random.NextDouble()<new[]{0.22,0.10,0.32}[groupIndex])await Event(c,t,study,session,participant,group,content[index],CanonicalInteractionEventTypes.LikeClicked,start.AddMilliseconds(elapsed+dwell/2),elapsed+dwell/2,null,sequence++);await Event(c,t,study,session,participant,group,content[index],CanonicalInteractionEventTypes.ContentMeaningfulExposureEnded,start.AddMilliseconds(elapsed+dwell),elapsed+dwell,dwell-650,sequence++);await Event(c,t,study,session,participant,group,content[index],CanonicalInteractionEventTypes.ContentExitedViewport,start.AddMilliseconds(elapsed+dwell+100),elapsed+dwell+100,null,sequence++);elapsed+=dwell+500;}await Event(c,t,study,session,participant,group,null,CanonicalInteractionEventTypes.SessionEnded,start.AddMilliseconds(duration),duration,null,sequence);
    }

    private static Task Event(SqliteConnection c,SqliteTransaction t,string study,string session,string participant,string group,string? content,string type,DateTime timestamp,long elapsed,long? duration,int sequence)=>Execute(c,t,"INSERT OR IGNORE INTO Events (Id,StudyId,SessionId,ParticipantId,GroupId,StimulusId,SnapshotStimulusId,EventType,TimestampUtc,ElapsedMilliseconds,DurationMilliseconds,SequenceNumber,MetadataJson) VALUES ($id,$study,$session,$participant,$group,NULL,$content,$type,$timestamp,$elapsed,$duration,$sequence,$metadata);",p=>{p.AddWithValue("$id",Stable(session,"event",sequence.ToString()));p.AddWithValue("$study",study);p.AddWithValue("$session",session);p.AddWithValue("$participant",participant);p.AddWithValue("$group",group);p.AddWithValue("$content",(object?)content??DBNull.Value);p.AddWithValue("$type",type);p.AddWithValue("$timestamp",timestamp.ToString("O"));p.AddWithValue("$elapsed",elapsed);p.AddWithValue("$duration",(object?)duration??DBNull.Value);p.AddWithValue("$sequence",sequence);p.AddWithValue("$metadata",JsonSerializer.Serialize(new{IsDemo=true,IsSynthetic=true,GeneratorVersion,GeneratorSeed}));});
    private static Task Classify(SqliteConnection c,SqliteTransaction t,string type,string id,string study,DateTime now)=>Execute(c,t,"INSERT OR IGNORE INTO ResearchDataClassifications (EntityType,EntityId,StudyId,IsDemo,IsSynthetic,ClassificationSource,CreatedAtUtc) VALUES ($type,$id,$study,1,1,$source,$created);",p=>{p.AddWithValue("$type",type);p.AddWithValue("$id",id);p.AddWithValue("$study",study);p.AddWithValue("$source",GeneratorVersion);p.AddWithValue("$created",now.ToString("O"));});
    private static async Task<string?> ParticipantIdAsync(SqliteConnection c,SqliteTransaction t,string study,string code){await using var command=c.CreateCommand();command.Transaction=t;command.CommandText="SELECT Id FROM Participants WHERE StudyId=$study AND ParticipantCode=$code LIMIT 1;";command.Parameters.AddWithValue("$study",study);command.Parameters.AddWithValue("$code",code);var value=Convert.ToString(await command.ExecuteScalarAsync());return string.IsNullOrWhiteSpace(value)?null:value;}
    private static async Task<List<string>> IdsAsync(SqliteConnection c,string sql,string study){var result=new List<string>();await using var command=c.CreateCommand();command.CommandText=sql;command.Parameters.AddWithValue("$study",study);await using var reader=await command.ExecuteReaderAsync();while(await reader.ReadAsync())result.Add(reader.GetString(0));return result;}
    private static async Task Execute(SqliteConnection c,SqliteTransaction t,string sql,Action<SqliteParameterCollection> parameters){await using var command=c.CreateCommand();command.Transaction=t;command.CommandText=sql;parameters(command.Parameters);await command.ExecuteNonQueryAsync();}
    private static string Utc(int seconds)=>new DateTime(2026,8,17,0,0,seconds,DateTimeKind.Utc).ToString("O");
    private static double Normal(Random random){var u1=Math.Max(double.Epsilon,random.NextDouble());var u2=random.NextDouble();return Math.Sqrt(-2*Math.Log(u1))*Math.Cos(2*Math.PI*u2);}
    private static string Stable(params string[] parts){var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(string.Join('|',parts)))).ToLowerInvariant();return "demo-"+hash[..28];}
}
